# Setup
title:               KAPS
tagline:             'KAPS Documentation'
description:         'A KAPS <a href="https://did-hub.github.io/KAPS/" target="_blank">Documentation</a>'
url:                 https://did-hub.github.io/KAPS/
baseurl:             ""
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              DC
  url:               https://did-hub.github.io/KAPS/
  email:             d.cho@kaps.gmbh

# Gems
plugins:
  - jekyll-paginate
  - bourbon

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
